# Site settings
title: Debokeh
email: katopz@debokeh.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://debokeh.com" # the base hostname & protocol for your site
twitter_username: katopz
github_username:  katopz

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: DEBOKEH
  location: AT
  social: BY
  credits: WITH

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/katopz
  - title: linkedin
    url: https://th.linkedin.com/pub/todsaporn-banjerdkit/27/54a/403
  - title: github
    url: http://github.com/katopz

# Postal address (add as many lines as necessary)
address:
  - line: Bangkok, Thailand

# Credits content
credits: 'Theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
